# Generated by Django 4.2.7 on 2023-11-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(blank=True, upload_to="produtos/"),
        ),
    ]
